version: "3"
services: 
    api:
        image: tdlback
        ports:
            - "8080:8080"
        networks:
            - tdlnet
    app:
        image: tdlfront
        ports:
            - "80:3000"
        depends_on:
            - api 
        networks:
            - tdlnet
networks: 
    tdlnet: